-- RadioTracker · Vercel + Supabase 多用户结构
-- 在一个全新的 Supabase 项目的 SQL Editor 中完整执行一次。

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.dramas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  missevan_id bigint,
  title text not null,
  platform text not null default '猫耳',
  source text not null default 'manual',
  kind text,
  categories text not null default '[]',
  organization text,
  abstract text,
  cover_url text,
  cover_local text,
  status text check (status is null or status in ('在听', '听完', '想听', '囤着', '搁置', '弃了')),
  purchased smallint not null default 0 check (purchased in (0, 1)),
  subscribed smallint not null default 0 check (subscribed in (0, 1)),
  heard_episodes integer check (heard_episodes is null or heard_episodes >= 0),
  total_episodes integer check (total_episodes is null or total_episodes >= 0),
  rating numeric(3, 2) check (rating is null or (rating >= 0 and rating <= 5)),
  finished_date date,
  rewatch_queued smallint not null default 0 check (rewatch_queued in (0, 1)),
  rewatch_status text,
  review text,
  serialize_status text,
  update_info text,
  update_day text,
  price numeric(10, 2),
  sync_saw_episode text,
  sync_total_episodes integer,
  sync_newest text,
  sync_serialize text,
  sync_purchased smallint,
  sync_subscribed smallint,
  synced_at timestamptz,
  bought_order integer,
  sub_order integer,
  sort_order integer not null default 0,
  detail_error text,
  detail_fetched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, missevan_id)
);

create table public.cvs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  missevan_id bigint,
  avatar_url text,
  note text,
  created_at timestamptz not null default now(),
  unique (user_id, name),
  unique (user_id, missevan_id)
);

create table public.drama_cvs (
  drama_id bigint not null references public.dramas(id) on delete cascade,
  cv_id bigint not null references public.cvs(id) on delete cascade,
  role_type text not null default '主役' check (role_type in ('主役', '配役')),
  character text,
  primary key (drama_id, cv_id, role_type)
);

create table public.sync_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  ran_at timestamptz not null default now(),
  kind text not null,
  added integer not null default 0,
  updated integer not null default 0,
  skipped integer not null default 0,
  detail text
);

-- 猫耳 Cookie 只允许 Vercel 服务端访问；内容使用 AES-256-GCM 加密。
create table public.user_missevan_credentials (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  missevan_user_id text not null,
  credential_ciphertext text not null,
  credential_iv text not null,
  saved_at timestamptz not null default now()
);

create table public.sync_jobs (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  running smallint not null default 0,
  step text,
  log text not null default '[]',
  error text,
  expired smallint not null default 0,
  started_at timestamptz,
  finished_at timestamptz
);

create table public.migration_state (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  completed_at timestamptz,
  source_checksum text
);

create index dramas_user_status_idx on public.dramas(user_id, status);
create index dramas_user_bought_idx on public.dramas(user_id, purchased, bought_order);
create index dramas_user_subscribed_idx on public.dramas(user_id, subscribed, sub_order);
create index dramas_user_finished_idx on public.dramas(user_id, finished_date);
create index drama_cvs_cv_idx on public.drama_cvs(cv_id);
create index sync_log_user_idx on public.sync_log(user_id, id desc);

-- 保留现有查询写法所需的 JSON 数组展开函数。
create or replace function public.json_each(input text)
returns table(value text)
language sql
immutable
set search_path = ''
as $$
  select jsonb_array_elements_text(coalesce(input, '[]')::jsonb)
$$;

alter table public.profiles enable row level security;
alter table public.dramas enable row level security;
alter table public.cvs enable row level security;
alter table public.drama_cvs enable row level security;
alter table public.sync_log enable row level security;
alter table public.user_missevan_credentials enable row level security;
alter table public.sync_jobs enable row level security;
alter table public.migration_state enable row level security;

create policy "profiles_self" on public.profiles
  for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_update_self" on public.profiles
  for update to authenticated using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "dramas_self" on public.dramas
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "cvs_self" on public.cvs
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "drama_cvs_self" on public.drama_cvs
  for all to authenticated
  using (exists (select 1 from public.dramas d where d.id = drama_id and d.user_id = (select auth.uid())))
  with check (exists (select 1 from public.dramas d where d.id = drama_id and d.user_id = (select auth.uid())));
create policy "sync_log_self" on public.sync_log
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "sync_jobs_self" on public.sync_jobs
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "migration_state_self" on public.migration_state
  for select to authenticated using ((select auth.uid()) = user_id);

-- user_missevan_credentials 没有客户端策略，只有服务端 service role 可访问。

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 封面文件由 Vercel 服务端写入；静态展示使用不可枚举的用户 UUID 路径。
insert into storage.buckets (id, name, public)
values ('drama-covers', 'drama-covers', true)
on conflict (id) do update set public = true;
