-- 每个用户、每部剧的听剧日记。服务端 API 会再次校验 user_id；
-- RLS 则保证即使以后开放 Supabase 客户端直连，也只能读取自己的内容。
create table if not exists public.drama_diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  drama_id bigint not null references public.dramas(id) on delete cascade,
  entry_date date not null default current_date,
  episode_label text,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists diary_user_drama_date_idx
  on public.drama_diary_entries(user_id, drama_id, entry_date desc, id desc);

alter table public.drama_diary_entries enable row level security;

drop policy if exists "diary_entries_self" on public.drama_diary_entries;
create policy "diary_entries_self" on public.drama_diary_entries
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.dramas d
      where d.id = drama_diary_entries.drama_id and d.user_id = (select auth.uid())
    )
  );
